server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r!
    oauth2:
      client:
        registration:
          google:
            clientId: 892581422150-r9hcs9dpiqan17ggsjvce8hdn66ligo5.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            clientId: 8_Ms_XK4KoiCWDupqbqM
            clientSecret: 37uCHSL5Jw
            scope:
              - email
              - name
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cyc-db1.cwlppyimbsxu.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220930
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml
